apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
  namespace: aks-demo
  labels:
    app: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      containers:
      - name: azure-vote-back
        image: redis:6.0
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
  namespace: aks-demo
spec:
  selector:
    app: azure-vote-back
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
  namespace: aks-demo
  labels:
    app: azure-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      containers:
      - name: azure-vote-front
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  namespace: aks-demo
spec:
  type: LoadBalancer
  selector:
    app: azure-vote-front
  ports:
  - port: 80
    targetPort: 80
